### PR TITLE
native: urbit auth recovery

### PR DESCRIPTION
**Pull request by arthyn**
This fixes TLON-2860 although doesn't address Galen's SQLite resetting comment.

We inject two functions as config to the urbit client, `getCode` and `handleAuthFailure`. In the self-hosted case, we don't store their `+code` so we just call `handleAuthFailure` and redirect them to login again. In the hosted case if we are still in a valid session with hosting, we can get our `+code` through the API and then authenticate with the urbit. If we're no longer in a valid hosting session, we call `handleAuthFailure` and redirect to the login screen.

We attempt a re-auth for any 403 failure of a scry (since we get the actual response status) and poke/subscribe/etc we simply try to auth if we encounter any error either directly through the call itself or through one of the error handlers we pass to those functions. Either way, we attempt to retry the same call that failed after successfully authenticating.

If we think that we can safely store the `+code`, then we should do that and then the self-hosted case will be more seamless. I'm just unfamiliar with the security of our storage system.

### CODE REVIEW

**Comment by patosullivan** [comment]
Maybe we could use expo-secure-store? https://docs.expo.dev/versions/latest/sdk/securestore/

**Comment by jamesacklin** [comment]
Does this replace #3999?

**Comment by arthyn** [comment]
@jamesacklin yep

**Review by patosullivan — APPROVED** [review]
Looks good. Feels like we could use expo-secure-store to store the +code, but we can look at that separately

**Review by latter-bolden — CHANGES_REQUESTED** [review]

**Review by latter-bolden — APPROVED** [review]
Looking good, excited to try it out

**Pull request merged**
