### PR TITLE
native: renovate ChannelHeader, add ChannelFooter

### PR DESCRIPTION
**Pull request by jamesacklin**
Fixes LAND-1890.

A preview of coming attractions:

Screenshot 2024-05-15 at 4 00 18 PM

### CODE REVIEW

**Comment by dnbrwstr** [comment]
Are you looking to merge this in? Or is it just up for preview purposes.

**Comment by jamesacklin** [comment]
@dnbrwstr Preview only, evaluating with @urcades with the help of the $2 Expo builds. I have a crashing bug in the build anyways.

**Comment by urcades** [comment]
@jamesacklin providing a spiritual stamp ㊙️

**Comment by jamesacklin** [comment]
Closing for now, keeping the branch around.

**Pull request closed without merging**
