### PR TITLE
message input: should autofocus in certain situations

### PR DESCRIPTION
**Pull request by patosullivan**
fixes TLON-2995
fixes TLON-2997
fixes TLON-2998

Adds a `shouldAutoFocus` prop to the MessageInput, which we turn on in every case for BigInput (so, when making or editing a notebook post or rich text gallery post) and for the case of starting a new thread in chat.

### CODE REVIEW

**Comment by jamesacklin** [comment]
I'm unable to get this to trigger in the iOS simulator. Did you test this on-device?

**Comment by patosullivan** [comment]
Tested in the sim, I'll look into it.

**Comment by patosullivan** [comment]
> I'm unable to get this to trigger in the iOS simulator. Did you test this on-device?

Should be fixed now.

**Review by latter-bolden — APPROVED** [review]
Code lgtm, @jamesacklin could you verify what you were seeing is fixed?

**Review by jamesacklin — APPROVED** [review]
Works for me!

**Pull request merged**
