### PR TITLE
move fixtures to app package, get cosmos working for web

### PR DESCRIPTION
**Pull request by patosullivan**
fixes TLON-3223

- Moves most of our fixtures to `/packages/app/fixtures`. (some mobile specific fixtures still exist in the `tlon-mobile` app package, and can still be selected in cosmos).
- Adds `cosmos:web`, `cosmos:native`, and `cosmos` scripts to the root. `cosmos` runs the two other scripts concurrently.
- Required forking cosmos to allow passing a new parameter to config, `fixturesLocation`.
- Removes old `tlon-web` fixtures and the cosmos dep there.

If you pull this down, run `pnpm i`, you should be able to run `pnpm cosmos` from the root and then see cosmos running at both `http://localhost:5000/` and `http://localhost:5001/`, one for the web and one for mobile.

Note: I couldn't get separate web fixtures working with this setup (yet). For now, any fixture in the `app` package should work on both platforms.

Also: I used gitpkg because react-cosmos is a monorepo, more about gitpkg here: https://gitpkg.vercel.app/about

Copilot description:
This pull request includes significant changes to the `tlon-mobile` and `tlon-web-new` applications to improve the configuration and module imports for React Cosmos. The most important changes include the removal of automatically generated files, updates to package dependencies, and adjustments to import paths and fixture configurations.

Configuration and Dependency Updates:

* [`apps/tlon-mobile/package.json`](diffhunk://#diff-8deea517552ee81bbb5b9943b366a4b19324af6c3ba8d60ee96aee46c8cc7fcbL148-R148): Updated the `react-cosmos` dependency to use a specific GitHub repository version.
* [`apps/tlon-web-new/package.json`](diffhunk://#diff-bbb45f66c81ab8935a1089904a9bf4614f52b4c0611f849b46f4c4bdc262f2d8L157-R158): Updated the `react-cosmos` and `react-cosmos-plugin-vite` dependencies to use specific GitHub repository versions.
* [`apps/tlon-web-new/cosmos.config.json`](diffhunk://#diff-8a625abec61bac179e202b40b6f11a11b0c8aa23b49c56cf36444a4bfeac6380R1-R12): Added a new Cosmos configuration file for the `tlon-web-new` application.

Import Path Adjustments:

* [`apps/tlon-mobile/src/App.cosmos.tsx`](diffhunk://#diff-7d52e70b8d9ce88fe2ec2b05a47cedc5bd14d3b4b42235bc385b67ef592d85afL4-R12): Updated the import path for `cosmos.imports` to reflect the correct directory structure.
* [`apps/tlon-mobile/src/fixtures/InputToolbar.fixture.tsx`](diffhunk://#diff-e83d9b0562a24db8f7bf3bed18318d4781eba0c6b56d24f586691f86a1484c3eR2-L6): Corrected the import path for `FixtureWrapper`.

Removal of Unnecessary Files and Code:

* [`apps/tlon-mobile/cosmos.imports.ts`](diffhunk://#diff-725c884ec6e8dad9b86a7a554f6efa5eb4e82d020dde0e0f5ca60025f8bea3d8L1-L135): Removed the automatically generated file and its content.
* [`apps/tlon-mobile/src/fixtures/FixtureWrapper.tsx`](diffhunk://#diff-d82a58c5db1f97b26c38cddc892e62e4c112760456301cb09a369ff54eee2599L1-L79): Removed the `FixtureWrapper` component and its related code.

Fixture Configuration Changes:

* [`apps/tlon-web-new/cosmos.imports.ts`](diffhunk://#diff-4f65d59df7a5483ccc8f7e8b6de299be46dbd08c66f322f75c8cc0349b8f7777R1-R25): Added a new Cosmos imports file for the `tlon-web-new` application.
* [`apps/tlon-web/src/components/About/__fixtures__`](diffhunk://#diff-39d8d9bcf31fe4f4a784f0a438e7f1881953a64e685d9efe065a86ac8e1d2b57L1-L5): Removed outdated fixture files for the About component. [[1]](diffhunk://#diff-39d8d9bcf31fe4f4a784f0a438e7f1881953a64e685d9efe065a86ac8e1d2b57L1-L5) [[2]](diffhunk://#diff-a31463f4f979fb293321bd5ab3c7b765c065c7b84675f31a0c18f2e651f2666fL1-L11) [[3]](diffhunk://#diff-3d438772b4199d2b377f74167a0044ee64b40f024fdaf970dfc0927bc40b6b89L1-L11)

### CODE REVIEW

**Comment by jamesacklin** [comment]
Haha, love a good patch. Gitpkg seems fine. Do you think your changes would make an improvement / apply to Cosmos upstream?

**Review by dnbrwstr — CHANGES_REQUESTED** [review]
Overall looks good!

A few small things:

- Is the root `cosmos.web.config.ts` used?
- Are any of the `cosmos.imports.ts` extraneous now?
- Can we use patch-package to make the cosmos change(s)? They are pretty small, and it would be nice to not have to update a separate repo to eg update cosmos version
- If patch-package doesn't work, can we fork cosmos to the tlon org so anyone at tlon can update?
- Probably would make sense to move react-cosmos (and possibly `react-cosmos-native`) deps to the root package.

**Comment by patosullivan** [comment]
> Overall looks good!
> 
> A few small things:
> 
> * Is the root `cosmos.web.config.ts` used?

yep, will remove.

> * Are any of the `cosmos.imports.ts` extraneous now?
the mobile one was, but I removed it. we now need the one in the root and the one in tlon-web-new.
> * Can we use patch-package to make the cosmos change(s)? They are pretty small, and it would be nice to not have to update a separate repo to eg update cosmos version
yep, I can do that, did it this way originally so I could easily test against their vite example package.

> * Probably would make sense to move react-cosmos (and possibly `react-cosmos-native`) deps to the root package.
good idea.

**Review by dnbrwstr — APPROVED** [review]
Lgtm!

**Pull request merged**
