### PR TITLE
native: + button on contacts screen for quick/bulk adding

### PR DESCRIPTION
**Pull request by latter-bolden**
OTT

Fixes TLON-3263

### CODE REVIEW

**Review by patosullivan — APPROVED** [review]
Looks good. Could we add it to ProfileScreenNavigator as well so it'll work on web?

**Comment by latter-bolden** [comment]
Good callout, thanks! Need to get better at remembering that kind of thing

**Review by jamesacklin — APPROVED** [review]
Conditionally approved pending displaying @ps in lieu of nicknames.

image

We should also fix the color-switching of sigils, but feel free to tack that on as a separate PR (if you have time before EOD—otherwise let's leave it for next week).

image

**Comment by latter-bolden** [comment]
@jamesacklin can you pull latest and check those two issues?

**Pull request merged**
