### PR TITLE
ChatOptionsSheet: mark group as read

### PR DESCRIPTION
**Pull request by jamesacklin**
Adds an optional prop to readGroup in activityApi to either mark the group read "deeply" or not (we badge it for new members requesting approval and clear the dot when navigating to it via Activity—this has nothing to do with unread messages in channels).

Adds a menu item to the ChatOptionsSheet for groups with unreads to deep-mark as read.

Fixes TLON-3240

### CODE REVIEW

**Review by latter-bolden — APPROVED** [review]
Passing deep accordingly does it. 

Only note is the UX is a little weird since it has to finish grabbing the unread before it shows the option. It lags a bit before popping in. Always including it and disabling if no unreads might be less jarring.

**Comment by jamesacklin** [comment]
Sweet, I'll proceed. Thanks!

> Always including it and disabling if no unreads might be less jarring.

I was thinking maybe I should pass it in _from_ the chat list item itself, then check to be sure once it's open.

**Comment by latter-bolden** [comment]
> I was thinking maybe I should pass it in from the chat list item itself, then check to be sure once it's open.

Even better :) ChatList data should be fresh

**Review by latter-bolden — APPROVED** [review]
Looks good! Thanks for the edit

**Pull request merged**
