### PR TITLE
native: implement filters and fuzzy search in main list

### PR DESCRIPTION
**Pull request by patosullivan**
fixes TLON-2229

looks like this:

https://github.com/tloncorp/tlon-apps/assets/1221094/5a40a843-5b48-4d81-a5bb-82cd40b1be7a

### CODE REVIEW

**Comment by jamesacklin** [comment]
Building a one-off to test in hand.

**Comment by jamesacklin** [comment]
Works great! One minor nit - we revert to the "Home" text on scroll when you hit the top of the scroll. See the latter half of this video. We probably just need to make that as dynamic as the rest of the title-text logic.

https://github.com/tloncorp/tlon-apps/assets/748181/6db03fea-446b-447b-8ab2-4d0fe7df9ecd

**Review by jamesacklin — APPROVED** [review]

**Review by dnbrwstr — CHANGES_REQUESTED** [review]
Few things here:
- Some animation jank (see video)
- Results lag, should debounce or optimize render
- Search input should not autocapitalize or spell correct query
- Can't search by @p

https://github.com/tloncorp/tlon-apps/assets/357216/6f04b57e-0b68-4348-87f3-9338c29927e3

**Comment by jamesacklin** [comment]
Playing good-cop/bad-cop: if we rip the fuzzy search input out and just show the tabset on overscroll, that would go a long way. We can rectify in another unit of work.

**Review by dnbrwstr — APPROVED** [review]
Nice, lgtm!

**Pull request merged**
